/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideMenu: typeof import('./src/components/navigation/AsideMenu.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    NavMenu: typeof import('./src/components/navigation/NavMenu.vue')['default']
    RecursiveChild: typeof import('./src/components/navigation/RecursiveChild.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
