export enum Api {
  RobotQuery = '/api/robotQuery',
  RobotAdd = '/api/robotAdd',
  RobotDelete = '/api/robotDelete',
  RobotUpdate = '/api/robotUpdate',
  ChartData4 = '/api/chartData4',
  ChartData = '/api/chartData',
  ChartData2 = '/api/chartData2',
  ChartData3 = '/api/chartData3',
  CountryList = '/api/countryList',
  MarkerList = '/api/markerList',
  Login = '/api/login',
  OrderQuery = '/api/orderQuery',
  OrderDelete = '/api/orderDelete',
  AddressList = '/api/addressList',
}
