import {
  DataScreen,
  KnifeFork,
  SurveillanceCameras,
  RobotOne,
  Excel,
  LocalTwo,
  Tag,
  Order,
  Find,
  Bill,
  Tool,
  LightMember,
  CooperativeHandshake,
  System,
  People,
} from '@icon-park/vue-next'
import type { Component } from 'vue'

export const name2icon = new Map<string, Component>([
  ['DataScreen', DataScreen],
  ['KnifeFork', KnifeFork],
  ['SurveillanceCameras', SurveillanceCameras],
  ['RobotOne', RobotOne],
  ['Excel', Excel],
  ['LocalTwo', LocalTwo],
  ['Tag', Tag],
  ['Order', Order],
  ['Find', Find],
  ['Bill', Bill],
  ['Tool', Tool],
  ['LightMember', LightMember],
  ['CooperativeHandshake', CooperativeHandshake],
  ['System', System],
  ['People', People],
])
